# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generative_agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16generative_agent.proto\x12\x12generative_service\"\'\n\x11PredictionRequest\x12\x12\n\ninput_data\x18\x01 \x01(\t\"5\n\x12PredictionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2w\n\x1bGenerativePredictionService\x12X\n\x07Predict\x12%.generative_service.PredictionRequest\x1a&.generative_service.PredictionResponseb\x06proto3')



_PREDICTIONREQUEST = DESCRIPTOR.message_types_by_name['PredictionRequest']
_PREDICTIONRESPONSE = DESCRIPTOR.message_types_by_name['PredictionResponse']
PredictionRequest = _reflection.GeneratedProtocolMessageType('PredictionRequest', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONREQUEST,
  '__module__' : 'generative_agent_pb2'
  # @@protoc_insertion_point(class_scope:generative_service.PredictionRequest)
  })
_sym_db.RegisterMessage(PredictionRequest)

PredictionResponse = _reflection.GeneratedProtocolMessageType('PredictionResponse', (_message.Message,), {
  'DESCRIPTOR' : _PREDICTIONRESPONSE,
  '__module__' : 'generative_agent_pb2'
  # @@protoc_insertion_point(class_scope:generative_service.PredictionResponse)
  })
_sym_db.RegisterMessage(PredictionResponse)

_GENERATIVEPREDICTIONSERVICE = DESCRIPTOR.services_by_name['GenerativePredictionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTIONREQUEST._serialized_start=46
  _PREDICTIONREQUEST._serialized_end=85
  _PREDICTIONRESPONSE._serialized_start=87
  _PREDICTIONRESPONSE._serialized_end=140
  _GENERATIVEPREDICTIONSERVICE._serialized_start=142
  _GENERATIVEPREDICTIONSERVICE._serialized_end=261
# @@protoc_insertion_point(module_scope)
