# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hamiltonian_agent.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'hamiltonian_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17hamiltonian_agent.proto\x12\x13hamiltonian_service\"\'\n\x11PredictionRequest\x12\x12\n\ninput_data\x18\x01 \x01(\t\"9\n\x12PredictionResponse\x12\x12\n\nprediction\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\t2z\n\x1cHamiltonianPredictionService\x12Z\n\x07Predict\x12&.hamiltonian_service.PredictionRequest\x1a\'.hamiltonian_service.PredictionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hamiltonian_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREDICTIONREQUEST']._serialized_start=48
  _globals['_PREDICTIONREQUEST']._serialized_end=87
  _globals['_PREDICTIONRESPONSE']._serialized_start=89
  _globals['_PREDICTIONRESPONSE']._serialized_end=146
  _globals['_HAMILTONIANPREDICTIONSERVICE']._serialized_start=148
  _globals['_HAMILTONIANPREDICTIONSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
