# Use an official Python image as a base
FROM python:3.12

# Set the working directory in the container
WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy backend files
COPY . /app/

# Expose port 5000
EXPOSE 5000

# Run the Flask application
CMD ["python", "app.py"]

